language: python
sudo: false
python:
- '2.7'
virtualenv:
  system_site_packages: false
addons:
  apt:
    packages:
    - python-pip
cache:
  directories:
  - "$HOME/.cache"
  - "$HOME/.ccache"
before_install:
- ccache -s
- export PATH=/usr/lib/ccache:${PATH}
- pip install --upgrade pip
install:
- pip install git+https://github.com/simphony/simphony-common.git@${SIMPHONY_VERSION}#egg=simphony
- pip install -r dev_requirements.txt
- python setup.py develop
- flake8 .
- simphony-meta-generate meta_class yaml_files/simphony_metadata.yml simphony_metadata/scripts/tests/meta_class -O
- simphony-meta-generate keywords yaml_files/cuba.yml simphony_metadata/scripts/tests/keywords.py
- simphony-meta-generate cuba_enum yaml_files/cuba.yml yaml_files/simphony_metadata.yml simphony_metadata/scripts/tests/cuba.py
script:
- coverage run -m unittest discover -v -p test*
after_success:
- pip install codecov
- codecov
