language: python
sudo: false
python:
  - '2.7'
virtualenv:
  system_site_packages: false
addons:
  apt:
    packages:
      - python-pip
cache:
  directories:
    - "$HOME/.cache"
    - "$HOME/.ccache"
before_install:
  - ccache -s
  - export PATH=/usr/lib/ccache:${PATH}
  - pip install --upgrade pip
install:
  - pip install -r dev_requirements.txt
script:
  - yamllint -s -c .yamllint yaml_files/
  - mkdir -p simphony/core/
  - mkdir -p simphony/cuds/meta/
  - simphony-meta-generate yaml_files simphony --overwrite
